GET http://localhost:3001/users

###

POST http://localhost:3001/users
Content-Type: application/json

{
  "first": "Ava",
  "last": "Cunningham",
  "username": "lillyprincess",
  "password": "500500"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
  "first": "Bob",
  "last": "Cunningham",
  "username": "bobcunnin",
  "password": "oooo4185"
}