// Get Users List
GET http://localhost:3001/users

###

// Register User
POST http://localhost:3001/users
Content-Type: application/json

{
  "first": "Test7",
  "last": "Test7",
  "username": "test7",
  "password": "testing"
}

###

// Login
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "bobcunnin",
  "password": "oooo4185"
}

###

// Member List
GET http://localhost:3001/members

###