// Get Users List
GET http://localhost:3001/users

###

// Register User
POST http://localhost:3001/sign-up
Content-Type: application/json

{
  "first": "test1",
  "last": "test11",
  "username": "test",
  "password": "testing"
}

###

// Login
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "test",
  "password": "testing"
}

###

// Logout
GET http://localhost:3001/logout

###

// Member List
GET http://localhost:3001/members

###